baseURL = 'https://blog.akop.dev/'
languageCode = 'en-us'
title = 'Backend Software Engineer'
theme = 'rose-pine'

[params]
author = "Akop Kesheshyan"
user = "blog"
hostname = "akop.dev"

[taxonomies]
tag = "tags"
category = "categories"

[[params.social]]
key = 0
name = "github"
url = "https://github.com/akopdev"

[[params.social]]
key = 1
name = "twitter"
url = "https://twitter.com/akopdev"

[[params.social]]
key = 2
name = "linkedin"
url = "https://www.linkedin.com/in/akopdev"

[[params.social]]
key = 3
name = "email"
url = "mailto:hello@akop.dev"

[menu]
  [[menu.header]]
    name = "notes"
    weight = 0
    url = "notes"

  [[menu.header]]
    name = "about"
    weight = 1
    url = "about"
